// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Samin Yeasar

/**
 * WASM loader abstraction for Vell.
 *
 * Supports three environments:
 *   - **Browser**: loads the WASM via dynamic import
 *   - **Node.js**: loads the WASM via dynamic import
 *   - **Deno**: loads the WASM via dynamic import (Deno supports npm: specifiers)
 *
 * Usage:
 *   import { setWasmModule, getWasmModule, initWasm } from "@solez-ai/vell";
 *
 *   // Option A: Auto-load (browser/Node.js/Deno)
 *   await initWasm();
 *
 *   // Option B: Manual registration (for custom setups)
 *   import * as wasm from "@solez-ai/vell/pkg/vell_wasm.js";
 *   setWasmModule(wasm);
 */

/** WASM module interface exposed by the generated vell-wasm crate. */
export interface VellWasmModule {
  parse_to_json(source: string): string;
  validate(source: string): string;
  get_version(): string;
  format_source(source: string): string;
}

let wasmModule: VellWasmModule | undefined;

/** Installs a WASM module implementation. */
export function setWasmModule(module: VellWasmModule): void {
  wasmModule = module;
}

/** Returns the installed WASM module or throws a descriptive error. */
export function getWasmModule(): VellWasmModule {
  if (!wasmModule) {
    throw new Error(
      "Vell WASM module has not been loaded. " +
        "Call setWasmModule(module) first, or await initWasm() to auto-load.\n" +
        "In the browser: include <script src='node_modules/@solez-ai/vell/pkg/vell_wasm.js'></script>\n" +
        "In Node.js:    await import('@solez-ai/vell/pkg/vell_wasm.js')\n" +
        "In Deno:       await initWasm() automatically detects the environment.",
    );
  }
  return wasmModule;
}

/** Returns true if the WASM module has been loaded. */
export function isWasmLoaded(): boolean {
  return wasmModule !== undefined;
}

// ---------------------------------------------------------------------------
// Shared import helper
// ---------------------------------------------------------------------------

/**
 * Tries to import the WASM module from one or more paths.
 * Uses variables to bypass TypeScript's static module resolution
 * (pkg/ is auto-generated by build:wasm and doesn't exist at typecheck time).
 */
async function tryLoadWasm(paths: string[], context: string): Promise<VellWasmModule> {
  for (const p of paths) {
    try {
      const m: VellWasmModule = await import(p) as VellWasmModule;
      setWasmModule(m);
      return m;
    } catch {
      // try next path
    }
  }
  throw new Error(
    `Failed to load Vell WASM in ${context}. ` +
      "Ensure the package includes the compiled WASM files in pkg/. " +
      "Run `npm run build:wasm` in the @solez-ai/vell package first.",
  );
}

// ---------------------------------------------------------------------------
// Environment-specific init functions
// ---------------------------------------------------------------------------

async function initWasmNode(): Promise<VellWasmModule> {
  return tryLoadWasm(
    ["../pkg/vell_wasm.js", "@solez-ai/vell/pkg/vell_wasm.js"],
    "Node.js",
  );
}

async function initWasmDeno(): Promise<VellWasmModule> {
  return tryLoadWasm(
    ["../pkg/vell_wasm.js", "@solez-ai/vell/pkg/vell_wasm.js"],
    "Deno",
  );
}

async function initWasmBrowser(wasmPath?: string): Promise<VellWasmModule> {
  return tryLoadWasm(
    [wasmPath || "../pkg/vell_wasm.js", "@solez-ai/vell/pkg/vell_wasm.js"],
    "the browser",
  );
}

// ---------------------------------------------------------------------------
// Public auto-loader
// ---------------------------------------------------------------------------

/**
 * Auto-loads the WASM module by detecting the runtime environment.
 *
 * - **Node.js**: imports `../pkg/vell_wasm.js` with npm scoped fallback
 * - **Deno**: same as Node.js (Deno supports npm: specifiers natively)
 * - **Browser**: tries the provided wasmPath, falls back to local pkg/
 *
 * @param wasmPath Optional path override (used in browser environments).
 */
export async function initWasm(wasmPath?: string): Promise<VellWasmModule> {
  if (wasmModule) return wasmModule;

  // Detect Deno — uses globalThis to avoid TypeScript 'Deno not found' errors
  if (typeof (globalThis as Record<string, unknown>).Deno !== "undefined") {
    return initWasmDeno();
  }

  // Detect Node.js
  if (typeof process !== "undefined" && process.versions?.node) {
    return initWasmNode();
  }

  // Assume browser
  return initWasmBrowser(wasmPath);
}
